# Generated by Django 5.1.1 on 2024-10-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('anw_a', models.CharField(max_length=255)),
                ('anw_b', models.CharField(max_length=255)),
                ('anw_c', models.CharField(max_length=255)),
                ('anw_d', models.CharField(max_length=255)),
                ('anw', models.CharField(max_length=1)),
                ('anw_correct', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('accuracy', models.IntegerField()),
            ],
        ),
    ]
