# Generated by Django 5.1.1 on 2024-11-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='number_of_questions',
            field=models.IntegerField(default=5),
        ),
    ]
