# Generated by Django 5.1.1 on 2024-11-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='level_class',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name=255),
        ),
    ]
